markdown: kramdown

minima:  
  skin: dark

theme: minima

navigation:
  - title: "Home"
    url: /
  - title: "Guides"
    url: /guides/

collections:
  guides:
    output: true
    permalink: /guides/:path/