markdown: kramdown

remote_theme: jekyll/minima #Use remote_theme for newer build
plugins:
  - jekyll-remote-theme
  
minima:  
  skin: dark



navigation:
  - title: "Home"
    url: /
  - title: "Guides"
    url: /guides/

collections:
  guides:
    output: true
    permalink: /guides/:path/